device: 'cpu'

dataset:
    x_size: 1
    y_size: 1
    max_num_context: 10
    batch_size: 64
    
encoder:
    num_layers: 2
    num_units: 128
    activation_cls: 'relu'

r_dim: 128

decoder:
    num_layers: 2
    num_units: 128
    activation_cls: 'relu'
    
    
lr: 1e-3
decay_rate: 0
num_epochs: 200000
